development:
  domain: localhost:3000
  sitename: Wakify (dev)
  site_slogan: Quick and Easy Wake-On-LAN
  footer_text: &copy; 2009 Matias Korhonen
  wol_port: 9
  wol_command: wakeonlan
  ping_command: ping
  captcha_enabled: true
  captcha_salt: 709b483739c8deddea3511fb1a0ff6477e035008
  captcha_lower_limit: 0
  captcha_upper_limit: 12
  ga_enabled: false
  ga_tracking_code: UA-xxxxxx-x
  contact_email: support@wakify.com

test:
  domain: test.host
  sitename: Wakify (test)
  site_slogan: Quick and Easy Wake-On-LAN
  footer_text: &copy; 2009 Matias Korhonen
  wol_port: 9
  wol_command: wakeonlan
  ping_command: ping
  captcha_enabled: false
  captcha_salt: 709b483739c8deddea3511fb1a0ff6477e035008
  captcha_lower_limit: 0
  captcha_upper_limit: 12
  ga_enabled: true
  ga_tracking_code: UA-xxxxxx-x
  contact_email: support@wakify.com
  
production:
  domain: wakify.com
  sitename: Wakify
  site_slogan: Quick and Easy Wake-On-LAN
  footer_text: &copy; 2009 Matias Korhonen
  wol_port: 9
  wol_command: wakeonlan
  ping_command: ping
  captcha_enabled: false
  captcha_salt: 709b483739c8deddea3511fb1a0ff6477e035008
  captcha_lower_limit: 0
  captcha_upper_limit: 12
  ga_enabled: true
  ga_tracking_code: UA-xxxxxx-x
  contact_email: support@wakify.com