development:
  domain: localhost:3000
  sitename: Wakify (dev)
  site_slogan: Quick and Easy Wake-On-LAN
  wol_port: 9
  wol_command: wakeonlan
  ping_command: ping
  captcha_enabled: true
  captcha_password: 27d02fea5971ff982f6c4c91d7f42635a9630ab0
  captcha_salt: 709b483739c8deddea3511fb1a0ff6477e035008
  ga_enabled: false
  ga_tracking_code: UA-xxxxxx-x

test:
  domain: test.host
  sitename: Wakify (test)
  site_slogan: Quick and Easy Wake-On-LAN
  wol_port: 9
  wol_command: wakeonlan
  ping_command: ping
  captcha_enabled: false
  captcha_password: 27d02fea5971ff982f6c4c91d7f42635a9630ab0
  captcha_salt: 709b483739c8deddea3511fb1a0ff6477e035008
  ga_enabled: true
  ga_tracking_code: UA-xxxxxx-x
  
production:
  domain: wakify.com
  sitename: Wakify
  site_slogan: Quick and Easy Wake-On-LAN
  wol_port: 9
  wol_command: wakeonlan
  ping_command: ping
  captcha_enabled: false
  captcha_password: 27d02fea5971ff982f6c4c91d7f42635a9630ab0
  captcha_salt: 709b483739c8deddea3511fb1a0ff6477e035008
  ga_enabled: true
  ga_tracking_code: UA-xxxxxx-x